USE [master]
GO

/****** Object:  Database [1K]    Script Date: 3/25/2023 2:45:18 AM ******/
CREATE DATABASE [1K]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'1K', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\1K.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'1K_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\1K_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [1K].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [1K] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [1K] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [1K] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [1K] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [1K] SET ARITHABORT OFF 
GO

ALTER DATABASE [1K] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [1K] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [1K] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [1K] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [1K] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [1K] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [1K] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [1K] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [1K] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [1K] SET  DISABLE_BROKER 
GO

ALTER DATABASE [1K] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [1K] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [1K] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [1K] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [1K] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [1K] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [1K] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [1K] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [1K] SET  MULTI_USER 
GO

ALTER DATABASE [1K] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [1K] SET DB_CHAINING OFF 
GO

ALTER DATABASE [1K] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [1K] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [1K] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [1K] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [1K] SET QUERY_STORE = OFF
GO

ALTER DATABASE [1K] SET  READ_WRITE 
GO


